---
Name: huubl-elemental-base
---
DNADesign\Elemental\Models\BaseElement:
  extensions:
    - Huubl\ElementalBase\Extensions\BaseElementExt

Dynamic\Elements\Flexslider\Elements\ElementSlideshow:
  extensions:
    -  Huubl\ElementalBase\Models\StyledTitle
  title_alignment_variants:
    text-left: 'left'
    text-right: 'right'
